- hosts: localhost
  connection: local

  vars:
    pip_install_packages:
      - name: docker
    dokku_version: v0.20.4

  tasks:
      
    - name: Install Role PIP
      local_action: command ansible-galaxy install -f geerlingguy.pip 

    - name: Install Role Docker
      local_action: command ansible-galaxy install -f geerlingguy.docker

    - name: Check if PIP is already installed
      stat: path=/usr/bin/pip
      register: pip_exists

    - name: Check if Docker is already installed
      stat: path=/usr/bin/docker
      register: docker_exists

    - name: Applying role PIP
      command: mv ~/.ansible/roles/geerlingguy.pip ~/.ansible/roles/pwslab.pip
      when: not pip_exists.stat.exists
      ignore_errors: yes

    - name: Applying role Docker
      command: mv ~/.ansible/roles/geerlingguy.docker ~/.ansible/roles/pwslab.docker
      when: not docker_exists.stat.exists
      ignore_errors: yes

    - name: Check the version of CentOS
      command: cat /etc/centos-release
      register: cent_os
      ignore_errors: yes

    - name: Check if version of Ubuntu
      shell: |
        lsb_release -d
      register: ubuntu_os
      ignore_errors: yes

    - name: Applying replacement on 20.04 or 8
      lineinfile:
          dest: ~/.ansible/roles/pwslab.pip/defaults/main.yml
          regexp: '^pip_package: '
          line: 'pip_package: python3-pip'
          state: present
      when:
        - cent_os.stdout | regex_search("8") or ubuntu_os.stdout | regex_search("20.04")

    - name: Installing PIP
      include_role:
        name: pwslab.pip
      when: not pip_exists.stat.exists
    
    - name: Installing Docker
      include_role:
          name: pwslab.docker
      when: not docker_exists.stat.exists

    - name: Get the Code Version
      get_url:
        url: https://raw.githubusercontent.com/dokku/dokku/{{ dokku_version }}/bootstrap.sh
        dest: ~/bootstrap.sh
    
    - name: Executing dokku
      command: sudo DOKKU_TAG={{ dokku_version }} bash bootstrap.sh
